name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    env:
      REACT_APP_JWT_SECRET: "1234"
      REACT_APP_KEYVALUE_DB_ADDRESS: "false key"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        run: npm run cypress:run > cypress-results
        with:
          start: npm start
          wait-on: http://localhost:3000

      - name: Get cypress results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: ./cypress-results

      - name: Get cypress screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
