name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    env:
      REACT_APP_JWT_SECRET: "1234"
      REACT_APP_KEYVALUE_DB_ADDRESS: "false key"

    steps:
      - name: Install dependencies
        run: npm install

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          start: |
            ipfs daemon --enable-pubsub-experiment >ipfs-daemon-std-logs 2>ipfs-daemon-err-logs &
            npm start
          wait-on: "http://localhost:3000"

      - name: Get ipfs-daemon-std-logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ipfs-daemon-std-logs
          path: ipfs-daemon-std-logs

      - name: Get ipfs-daemon-err-logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ipfs-daemon-err-logs
          path: ipfs-daemon-err-logs


      - name: Get screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Get videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
